# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "github-actions-pilpline"
  EB_APPLICATION_NAME       : "github-actions-lesson-app"
  EB_ENVIRONMENT_NAME       : "Githubactionslessonapp-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-west-1"
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  my_ci_part:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git clone our repo
        uses: actions/checkout@v2
        
      - name: Create ZIP deployment package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        
      - name: Configure my AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id        : ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws-secret-access-key    : ${{ secrets.MY_AWS_SECRET_KEY }}
          aws-region               : ${{ env.AWS_REGION_NAME }}
          
      - name: Copy Deployment package to S3 bucket
        run : aws s3 sp ${{ env.DEPLOY_PACKAGE_NAME }}  s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
        
      - name: Happy Message for SI finish
        run : echo Happy New Year!
        

